[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["prototypes/**/email-*.html"]

[context.deploy-preview.environment]
  IS_PREVIEW = "true"
